services:
  ingestion:
    build:
      context: .
      dockerfile: ingestion/Dockerfile
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    profiles:
      - pipeline

  prepare:
    build:
      context: .
      dockerfile: ingestion/Dockerfile      # riusa la stessa immagine di ingestion
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    command: python run_prepare.py
    profiles:
      - pipeline

  signals:
    build:
      context: .
      dockerfile: signals/Dockerfile
    volumes:
      - ./data:/app/data
    depends_on:
      - ingestion
    environment:
      - PYTHONUNBUFFERED=1
    profiles:
      - pipeline

  dashboard:
    env_file:
      - .env
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8501:8501"
    mem_limit: 8g          # ← aggiungi questa riga
    memswap_limit: 8g  

  scheduler:
    build:
      context: .
      dockerfile: ingestion/Dockerfile
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    command: python update_scheduler.py
    restart: unless-stopped
    profiles:
      - update

    #update marginals e inverted index 
